### ISSUE TITLE
getConfigBlock for channel vschannel failed with peer peer0.sharing.example.com.

### ISSUE THREAD

**Issue by yiwenlong** [tomxucnxa/vehiclesharing#10]
Hi，你好！
我将这个Demo程序中的peer0.Sharing、orderer、peer0.Vehile分别部署到三个不同地点的物理主机上面，我本地的电脑作为客户端。
我自己仿照 hyperledger/fabric-samples/fabcar/java 中的代码写了Java版的客户端去尝试调用chaincode中的接口。但是会报如下错误：
```
org.hyperledger.fabric.gateway.GatewayRuntimeException: org.hyperledger.fabric.sdk.exception.ProposalException: org.hyperledger.fabric.sdk.exception.TransactionException: org.hyperledger.fabric.sdk.exception.ProposalException: getConfigBlock for channel vschannel failed with peer peer0.sharing.example.com.  Status FAILURE, details: Channel Channel{id: 1, name: vschannel} Sending proposal with transaction: cc5bf1d6d169623106a14fb0a413d0aa97947242c3024888bcae5a6bfa7ff802 to Peer{ id: 2, name: peer0.sharing.example.com, channelName: vschannel, url: grpc://120.78.152.48:7051, mspid: SharingMSP} failed because of: gRPC failure=Status{code=INTERNAL, description=channelRead() missed by ProtocolNegotiator handler: PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 1024)
Channel Pipeline: [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$WaitUntilActiveHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0], cause=null}
	at org.hyperledger.fabric.gateway.impl.QueryImpl.evaluate(QueryImpl.java:38)
	at org.hyperledger.fabric.gateway.impl.SingleQueryHandler.evaluate(SingleQueryHandler.java:41)
	at org.hyperledger.fabric.gateway.impl.TransactionImpl.evaluate(TransactionImpl.java:190)
	at org.hyperledger.fabric.gateway.impl.ContractImpl.evaluateTransaction(ContractImpl.java:55)
...
```

我试过直接将代码上传到peer0.Sharing所在的主机，代码执行没有问题。然后我在本地使用fabric-tools 执行query 和invoke 也没有问题。

请问这是怎么回事？我想通过Java去访问chaincode中的接口，你可以帮我提供一个解决问题的思路吗？
非常感谢！

**Comment by tomxucnxa** [comment]
您是通过JAVA SDK 访问吗？建议检查connection profile, 保证其中有需要的PEER， ORDERER信息。既然FABRIC TOOL没问题，那说明系统、CHAINCODE肯定是好的。请再次检查JAVA CLIENT.

**Comment by yiwenlong** [comment]
我找了另外一台电脑运行我的代码，是可以访问到的，应该是我电脑本地的某些配置影响了。但我没有弄明白是什么配置影响了我访问远程的peer和orderer节点。我host配置应该没有问题的，不然fabric-tool应该也访问不到。
请问您知道电脑本地会有哪些因素会有影响吗？我是mac系统。

**Comment by tomxucnxa** [comment]
fabric-tool 是通过DOCKER NETWORK访问的，实际它是访问LOCALHOST的不同端口。而其他程序则需要注意HOST。建议检查 HOST，PORT。是否真正可以被访问。

**Comment by tomxucnxa** [comment]
这个错误不好判断。可能有很多原因：HOST，PORT；JAVA LIB；CONNECTION PROFILE。
或者你也可以先试下使用其他NODE SDK写一个客户端程序 试试。

**Comment by yiwenlong** [comment]
我最终确认过了，是网络问题。我把orderer节点部署在了香港，会经常访问不到
